In [ ]:
#Dataframes 

!pip install pandas
import pandas as pd 


df = pd.DataFrame([2,3,4,5,2,2])
display(df)

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Siddhanth\AppData\Roaming\Python\Python313\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Siddhanth\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Siddhanth\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Siddhanth\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Siddhanth\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\Siddhanth\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

   0
0  2
1  3
2  4
3  5
4  2
5  2

In [10]:
# #data Methods 
# df.info()
# df.describe()

# #adding columns in the df 
df["new"] = [2,3,4,5,2,2]
display(df)

#droping columns 
# df = df.drop(columns = ['new'])
# display(df)

#updating vlues specifically 
df.loc[df['new'] == 2] = 10
df

   0  new
0  2    2
1  3    3
2  4    4
3  5    5
4  2    2
5  2    2

    0  new
0  10   10
1   3    3
2   4    4
3   5    5
4  10   10
5  10   10

#Indexing and Selection

In [ ]:
# df.set_index('new', inplace = True)
# df.query('new == 10')

# #methods
# .fillna()
# .dropna()
# .isnull()
# .notnull()
# .value_counts()
# .unique()
# .nunique()
# .sort_values()
# .sort_index()   
# .mean()
# .median()
# .mode() 
# .std()
# .var()          
# .sum()
# .count()    
# .min()
# .max()  
# .astype()
# .str.upper()
# .str.lower()
# .str.contains()
# .str.replace()  
# .str.split()
# .str.strip()
# .str.len()
# .str.startswith()
# .str.endswith()
# .str.isalpha()
# .str.isdigit()  
# .str.isalnum()
# .str.islower()
# .str.isupper()
# .str.isspace()
# .str.capitalize()
# .str.title()
# .str.swapcas

      0
new
10   10
10   10
10   10

In [14]:
new_data = { 'Name': ['Alice', 'Bob', 'Charlie', 'Charlie', 'David','David', 'Eve', 'Alice', 'Alice','Alice','Bob', 'Charlie', 'David'],
             'Bought': [25, 30, 35, 40, 45, 25, 30, 35, 40, 25, 30, 35, 40],}

df = pd.DataFrame(new_data)
df.set_index('Name', inplace = True)

grouping = df.groupby('Name')
display(grouping)

grouping.sum()

         Bought
Name
Alice       125
Bob          60
Charlie     110
David       110
Eve          30

In [ ]:
#questionaire 

df1 = pd.DataFrame([2,3,4,1])
df2 = pd.DataFrame([5,6,7,8])

pd.merge(df1,df2, how = 'inner')

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Kabir', 'Sneha', 'Aryan', 'Meera'],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'IT'],
    'Marks': [85, 72, np.nan, 90, 66, 78],
    'Age': [21, 22, 20, 23, np.nan, 21]
})